apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- httpbin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: oauth2-proxy
  files:
  - authenticated_emails.csv

secretGenerator:
- name: oauth2-proxy
  type: Opaque
  literals:
  - client-id=https://kubernetes.default.svc.cluster.local
  - client-secret=dummy
  - cookie-secret=Apwen2DmHT2z7lq3iAZ7sg==

patchesStrategicMerge:
- oauth2-proxy-sidecar.yaml
