apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- oauth2-proxy.yaml
- httpbin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: oauth2-proxy
  behavior: replace
  files:
  - oauth2_proxy.cfg
  - authenticated_emails.csv

secretGenerator:
- name: oauth2-proxy
  type: Opaque
  behavior: replace
  literals:
  - client-id=https://kubernetes.default.svc.cluster.local
  - client-secret=dummy
  - cookie-secret=Apwen2DmHT2z7lq3iAZ7sg==

patchesStrategicMerge:
- patch-emails.yaml
